### ISSUE TITLE
Full ERC20 and ERC721 compliance so balance shows the SUM of meallable and solidified NFTs

### ISSUE THREAD

**Issue by SmartLayer** [SmartTokenLabs/ST404#1]
Let's say m is the max number a user can put in transfer() function as the amount, and not get an error, balanceOf() should return that number.

if the user can only call transfer(addr, amount) with one number: 0 (because he has nothing), then balanceOf() returns nothing.

for example:
```
decimals = 2
balanceOf(user) = 500 (5.00 ERC20)
solidify(1)
balanceOf(user) = 400 (4.00 ERC20) + user's own 1 NFT which is 100 = 500
```
so return value of balanceOf() doesn't change no matter how many are solidified.

**Comment by oleggrib** [comment]
@SmartLayer , contract updated according to requirements
