### ISSUE TITLE
not able to swap more than 110 STTT on Uniswap 

### ISSUE THREAD

**Issue by zhangzhongnan928** [SmartTokenLabs/ST404#3]
STTT: https://sepolia.etherscan.io/address/0x63f7ff78ebb6591445fbae524775c13715765098
https://app.uniswap.org/swap?exactField=output&exactAmount=110&outputCurrency=0x63F7fF78ebB6591445FbaE524775C13715765098&inputCurrency=eth

**Comment by oleggrib** [comment]
Hi @zhangzhongnan928  possibly uniswap has some gas limits
try this contract version, where Virtual ERC721 Transfer events disabled
https://sepolia.etherscan.io/address/0xc77f5b4e485714a4541b4acf7657d1f627823999

**Comment by SmartLayer** [comment]
The returnin gof the function of whitelist/exempt list should address it then.

> Hi @zhangzhongnan928 possibly uniswap has some gas limits try this contract version, where Virtual ERC721 Transfer events disabled https://sepolia.etherscan.io/address/0xc77f5b4e485714a4541b4acf7657d1f627823999

**Comment by oleggrib** [comment]
currently admin address is whitelisted(it will not emit ERC721 Transfer events), 
you can whitelist uniswapAddress, so when you send some ERC20 to uniswap then it will not emit any ERC721 Transfer

but when uniswap will transfer ERC20 to some user1 then it will skip ERC721 BURN events for uniswap and will emit ERC721 Transfer(0, user1, tokenId) 

in this case you can send any number or ERC20 to uniswap in single cheap transaction 

and uniswap bulk transfers to  some user will be 2 times cheaper 
@zhangzhongnan928 @SmartLayer

**Comment by SmartLayer** [comment]
sepolia
0xFedd0a4098dfe309366B6947F78C7bcB7fFe9442

Add to the pool
https://sepolia.etherscan.io/tx/0x14ab06fd8c966daa7a0ad965c4e2c3edb58a15f365f0263b236cabeeb3544c99
https://sepolia.etherscan.io/tx/0xd4edc0d6c4daa14fd475017972a336cfdb6b3bf85ab53cb49cdc4d54b16daedf

Swap 97 ETH -> ERC20
https://sepolia.etherscan.io/tx/0x7ee14ab9165e07d88b355077e78a3f214af24625583cb0d49341123fd6282d0f

Swap 95 ETH -> ERC20
https://sepolia.etherscan.io/tx/0xd88941e351a3dfbc474a2206ced24561ea9b960c57da76012609709c9f8d92c4

Swap 95 ETH -> ERC20
https://sepolia.etherscan.io/tx/0xb7033d25a341c00e6ab044b8d200d189f6f0e13212404714bbb169b40c2ea25a

Swap 200 ERC20 -> ETH
https://sepolia.etherscan.io/tx/0x2200d4940efd5c94c66e3f993f06e78febd1ec9cfe392a2e902a0aac5b84822a

mumbai
0xfe848c4597d9B4F5cC7FE2fb8067b6349b3C7551

Add to pool 2000 ERC20
https://mumbai.polygonscan.com/tx/0x22a4e4f10149a21533dbde1a3f3b1d84c2bbb69d118c29969ee41867ccd4adec

swap MATIC -> 120 ERC20
https://mumbai.polygonscan.com/tx/0xe5c95ed53fceff9c9826977215fe2208f559f64c9473a8f31c044d455f579052

swap 20 ERC20 -> MATIC 
https://mumbai.polygonscan.com/tx/0x7340d44b91718dce1795b4498afaa651056cfd7f1e641e5e731c2db7ca7d0428

Add to pool 4000 ERC20
https://mumbai.polygonscan.com/tx/0x0b1003d9e59d14f9ed301bd11d985416a13cf090fa97ad72e84c494adacce6f6

swap MATIC -> 120 ERC20
https://mumbai.polygonscan.com/tx/0xf83b9faec4e2ec5de3ccd2cf097d3c2243b2c09279cf02a9e59360de8dbade4f

swap 500 ERC20 -> MATIC 
https://mumbai.polygonscan.com/tx/0xa18cb514ae719a57738d428b125e7f06e47058a0cd069cc35832d8b6313636fc

Kudo to improvements made by Oleg
